["bin/bzr"]
decision = "provide"
file_entry_name = "/bin/bzr"
kind = "symlink"
resolution = "constant"

["bin/bzr".store_path]
hash = "jl40g5cdy6nvr90sfqxyfv5awmj94jbx"
name = "python3.10-breezy-3.3.2"
store_dir = "/nix/store"

["bin/bzr".store_path.origin]
attr = "breezy"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/cargo"]
decision = "provide"
file_entry_name = "/bin/cargo"
kind = "symlink"
resolution = "constant"

["bin/cargo".store_path]
hash = "qiklc9rr5jg1zck0rb7vj4wn1n7yxx67"
name = "cargo-1.67.1"
store_dir = "/nix/store"

["bin/cargo".store_path.origin]
attr = "cargo"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/darcs"]
decision = "provide"
file_entry_name = "/bin/darcs"
kind = "symlink"
resolution = "constant"

["bin/darcs".store_path]
hash = "icb53p92agly7zjkg316870xczd7zyn3"
name = "darcs-2.16.5"
store_dir = "/nix/store"

["bin/darcs".store_path.origin]
attr = "haskellPackages.darcs"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/fossil"]
decision = "provide"
file_entry_name = "/bin/fossil"
kind = "symlink"
resolution = "constant"

["bin/fossil".store_path]
hash = "801b33law28l1gz9pbnh9iyd28fvhmz5"
name = "fossil-2.21"
store_dir = "/nix/store"

["bin/fossil".store_path.origin]
attr = "fossil"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/gfortran"]
decision = "provide"
file_entry_name = "/bin/gfortran"
kind = "symlink"
resolution = "constant"

["bin/gfortran".store_path]
hash = "y4fkkgbylpqgadgq3n50x7g614sjbrmv"
name = "gfortran-wrapper-12.2.0"
store_dir = "/nix/store"

["bin/gfortran".store_path.origin]
attr = "gfortran"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/hg"]
decision = "provide"
file_entry_name = "/bin/hg"
kind = "symlink"
resolution = "constant"

["bin/hg".store_path]
hash = "v2s4kbgqfd0s9b6hd8b982azdca4m3l4"
name = "mercurial-6.3.3"
store_dir = "/nix/store"

["bin/hg".store_path.origin]
attr = "mercurial"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/lsb_release"]
decision = "provide"
file_entry_name = "/bin/lsb_release"
kind = "symlink"
resolution = "constant"

["bin/lsb_release".store_path]
hash = "ji55v58cch94h30inpnrd5h5jra9fwd8"
name = "lsb_release"
store_dir = "/nix/store"

["bin/lsb_release".store_path.origin]
attr = "lsb-release"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pgen"]
decision = "ignore"
resolution = "constant"

["bin/pijul"]
decision = "provide"
file_entry_name = "/bin/pijul"
kind = "symlink"
resolution = "constant"

["bin/pijul".store_path]
hash = "xdbsd1w90ln1ql1fr6a3lb7airck3l9i"
name = "pijul-1.0.0-beta.4"
store_dir = "/nix/store"

["bin/pijul".store_path.origin]
attr = "pijul"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pip"]
decision = "provide"
file_entry_name = "/bin/pip"
kind = "symlink"
resolution = "constant"

["bin/pip".store_path]
hash = "8gzj48mkr8i824a4ali025hk85gmfdzy"
name = "python3.10-pip-22.3.1"
store_dir = "/nix/store"

["bin/pip".store_path.origin]
attr = "python310Packages.pip"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pkg-config"]
decision = "provide"
file_entry_name = "/bin/pkg-config"
kind = "symlink"
resolution = "constant"

["bin/pkg-config".store_path]
hash = "prm4x2r6997idyjxajapk1177jczvjfj"
name = "pkg-config-0.29.2"
store_dir = "/nix/store"

["bin/pkg-config".store_path.origin]
attr = "pkg-config-unwrapped"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/rustc"]
decision = "provide"
file_entry_name = "/bin/rustc"
kind = "symlink"
resolution = "constant"

["bin/rustc".store_path]
hash = "bxm02qp0lnm4sin3x78qrxp0gsbby1jb"
name = "rustc-1.67.1"
store_dir = "/nix/store"

["bin/rustc".store_path.origin]
attr = "rustc"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/svnversion"]
decision = "provide"
file_entry_name = "/bin/svnversion"
kind = "symlink"
resolution = "constant"

["bin/svnversion".store_path]
hash = "qz3yz8b3ahcjlnk96415gy3ldk0x36zw"
name = "subversion-1.14.2"
store_dir = "/nix/store"

["bin/svnversion".store_path.origin]
attr = "subversion"
output = "out"
system = "x86_64-linux"
toplevel = true

["include/libunwind.h"]
decision = "ignore"
resolution = "constant"

["include/sys"]
decision = "ignore"
resolution = "constant"

["include/sys/endian.h"]
decision = "ignore"
resolution = "constant"

["include/tbb"]
decision = "ignore"
resolution = "constant"

["include/xlocale.h"]
decision = "ignore"
resolution = "constant"

["lib/pkgconfig/libffi.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/libffi.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/libffi.pc".store_path]
hash = "4j08mgygxhi9y3957hbwqn1bg02va18y"
name = "libffi-3.4.4-dev"
store_dir = "/nix/store"

["lib/pkgconfig/libffi.pc".store_path.origin]
attr = "libffi"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/openssl.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/openssl.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/openssl.pc".store_path]
hash = "fyiwac98bi86nd5qzz9bhvs1bvmmwgad"
name = "openssl-3.0.8-dev"
store_dir = "/nix/store"

["lib/pkgconfig/openssl.pc".store_path.origin]
attr = "openssl"
output = "dev"
system = "x86_64-linux"
toplevel = true

["share/aclocal/ax_zoneinfo.m4"]
decision = "provide"
file_entry_name = "/share/aclocal/ax_zoneinfo.m4"
kind = "symlink"
resolution = "constant"

["share/aclocal/ax_zoneinfo.m4".store_path]
hash = "0znwn1lw0268i7pj0rylhz9dnzbwijjn"
name = "autoconf-archive-2022.09.03"
store_dir = "/nix/store"

["share/aclocal/ax_zoneinfo.m4".store_path.origin]
attr = "autoconf-archive"
output = "out"
system = "x86_64-linux"
toplevel = true
