["bin/bison"]
decision = "provide"
file_entry_name = "/bin/bison"
kind = "symlink"
resolution = "constant"

["bin/bison".store_path]
hash = "lxa6vajnpck04xvv7cmmzy2nv62196n0"
name = "bison-3.8.2"
store_dir = "/nix/store"

["bin/bison".store_path.origin]
attr = "bison"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/cargo"]
decision = "provide"
file_entry_name = "/bin/cargo"
kind = "symlink"
resolution = "constant"

["bin/cargo".store_path]
hash = "qiklc9rr5jg1zck0rb7vj4wn1n7yxx67"
name = "cargo-1.67.1"
store_dir = "/nix/store"

["bin/cargo".store_path.origin]
attr = "cargo"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/ccache"]
decision = "provide"
file_entry_name = "/bin/ccache"
kind = "symlink"
resolution = "constant"

["bin/ccache".store_path]
hash = "gd6p18di7s7x97gj9hbpkfy1ml00n1yj"
name = "ccache-4.7.4"
store_dir = "/nix/store"

["bin/ccache".store_path.origin]
attr = "ccache"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/cmake"]
decision = "provide"
file_entry_name = "/bin/cmake"
kind = "symlink"
resolution = "constant"

["bin/cmake".store_path]
hash = "l341npqn3j8pwqq1nqgj5cqhnfbzhphd"
name = "cmake-3.25.1"
store_dir = "/nix/store"

["bin/cmake".store_path.origin]
attr = "cmake"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/dlltool"]
decision = "provide"
file_entry_name = "/bin/dlltool"
kind = "symlink"
resolution = "constant"

["bin/dlltool".store_path]
hash = "2299glr8ffi953qj4d8m3kfvj7dmrpxj"
name = "llvm-binutils-wrapper-15.0.7"
store_dir = "/nix/store"

["bin/dlltool".store_path.origin]
attr = "llvmPackages_15.bintools"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/flex"]
decision = "provide"
file_entry_name = "/bin/flex"
kind = "symlink"
resolution = "constant"

["bin/flex".store_path]
hash = "ids2lps1i2z3hkfl0n4wz983bqkzq6yh"
name = "flex-2.6.4"
store_dir = "/nix/store"

["bin/flex".store_path.origin]
attr = "flex"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/fop"]
decision = "provide"
file_entry_name = "/bin/fop"
kind = "symlink"
resolution = "constant"

["bin/fop".store_path]
hash = "5jmw2559a168dlgsrkjkygk2pl0fgy2c"
name = "fop-2.7"
store_dir = "/nix/store"

["bin/fop".store_path.origin]
attr = "fop"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/gfortran"]
decision = "provide"
file_entry_name = "/bin/gfortran"
kind = "symlink"
resolution = "constant"

["bin/gfortran".store_path]
hash = "y4fkkgbylpqgadgq3n50x7g614sjbrmv"
name = "gfortran-wrapper-12.2.0"
store_dir = "/nix/store"

["bin/gfortran".store_path.origin]
attr = "gfortran"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/lsb_release"]
decision = "provide"
file_entry_name = "/bin/lsb_release"
kind = "symlink"
resolution = "constant"

["bin/lsb_release".store_path]
hash = "ji55v58cch94h30inpnrd5h5jra9fwd8"
name = "lsb_release"
store_dir = "/nix/store"

["bin/lsb_release".store_path.origin]
attr = "lsb-release"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pgen"]
decision = "ignore"
resolution = "constant"

["bin/pip"]
decision = "provide"
file_entry_name = "/bin/pip"
kind = "symlink"
resolution = "constant"

["bin/pip".store_path]
hash = "8gzj48mkr8i824a4ali025hk85gmfdzy"
name = "python3.10-pip-22.3.1"
store_dir = "/nix/store"

["bin/pip".store_path.origin]
attr = "python310Packages.pip"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pkg-config"]
decision = "provide"
file_entry_name = "/bin/pkg-config"
kind = "symlink"
resolution = "constant"

["bin/pkg-config".store_path]
hash = "prm4x2r6997idyjxajapk1177jczvjfj"
name = "pkg-config-0.29.2"
store_dir = "/nix/store"

["bin/pkg-config".store_path.origin]
attr = "pkg-config-unwrapped"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/plfit"]
decision = "provide"
file_entry_name = "/bin/plfit"
kind = "symlink"
resolution = "constant"

["bin/plfit".store_path]
hash = "k9s15lqyry6kfgnb25j3li2bmyax4j22"
name = "plfit-0.9.4"
store_dir = "/nix/store"

["bin/plfit".store_path.origin]
attr = "python311Packages.plfit"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/rustc"]
decision = "provide"
file_entry_name = "/bin/rustc"
kind = "symlink"
resolution = "constant"

["bin/rustc".store_path]
hash = "bxm02qp0lnm4sin3x78qrxp0gsbby1jb"
name = "rustc-1.67.1"
store_dir = "/nix/store"

["bin/rustc".store_path.origin]
attr = "rustc"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/source-highlight"]
decision = "provide"
file_entry_name = "/bin/source-highlight"
kind = "symlink"
resolution = "constant"

["bin/source-highlight".store_path]
hash = "v1dcrny7x54syy0hsaprg095iv5ikjsm"
name = "source-highlight-3.1.9"
store_dir = "/nix/store"

["bin/source-highlight".store_path.origin]
attr = "sourceHighlight"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/svnversion"]
decision = "provide"
file_entry_name = "/bin/svnversion"
kind = "symlink"
resolution = "constant"

["bin/svnversion".store_path]
hash = "qz3yz8b3ahcjlnk96415gy3ldk0x36zw"
name = "subversion-1.14.2"
store_dir = "/nix/store"

["bin/svnversion".store_path.origin]
attr = "subversion"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/xmllint"]
decision = "provide"
file_entry_name = "/bin/xmllint"
kind = "symlink"
resolution = "constant"

["bin/xmllint".store_path]
hash = "fb30jz48v627dlqgqqwalwwszws588iv"
name = "libxml2-2.10.3-bin"
store_dir = "/nix/store"

["bin/xmllint".store_path.origin]
attr = "libxml2"
output = "bin"
system = "x86_64-linux"
toplevel = true

["bin/xmlto"]
decision = "provide"
file_entry_name = "/bin/xmlto"
kind = "symlink"
resolution = "constant"

["bin/xmlto".store_path]
hash = "3p72iwjl19dm5fcayc2bbh93iahh3kyd"
name = "xmlto-0.0.28"
store_dir = "/nix/store"

["bin/xmlto".store_path.origin]
attr = "xmlto"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/xsltproc"]
decision = "provide"
file_entry_name = "/bin/xsltproc"
kind = "symlink"
resolution = "constant"

["bin/xsltproc".store_path]
hash = "a2cnbdxv3yqs3s1drm766a6p3qnrqgh4"
name = "libxslt-1.1.37-bin"
store_dir = "/nix/store"

["bin/xsltproc".store_path.origin]
attr = "libxslt"
output = "bin"
system = "x86_64-linux"
toplevel = true

["include/libunwind.h"]
decision = "ignore"
resolution = "constant"

["include/sys"]
decision = "ignore"
resolution = "constant"

["include/sys/endian.h"]
decision = "ignore"
resolution = "constant"

["include/tbb"]
decision = "ignore"
resolution = "constant"

["include/xlocale.h"]
decision = "ignore"
resolution = "constant"

["lib/libxml2.so"]
decision = "provide"
file_entry_name = "/lib/libxml2.so"
kind = "symlink"
resolution = "constant"

["lib/libxml2.so".store_path]
hash = "hmh8yakhrp3r95b7r085m4xnzp8crz3b"
name = "libxml2-2.10.3"
store_dir = "/nix/store"

["lib/libxml2.so".store_path.origin]
attr = "libxml2"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/libffi.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/libffi.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/libffi.pc".store_path]
hash = "4j08mgygxhi9y3957hbwqn1bg02va18y"
name = "libffi-3.4.4-dev"
store_dir = "/nix/store"

["lib/pkgconfig/libffi.pc".store_path.origin]
attr = "libffi"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/libxml-2.0.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/libxml-2.0.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/libxml-2.0.pc".store_path]
hash = "0z5wasald7dmipjpbx8kw31pj0kzjxpg"
name = "libxml2-2.10.3-dev"
store_dir = "/nix/store"

["lib/pkgconfig/libxml-2.0.pc".store_path.origin]
attr = "libxml2"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/openssl.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/openssl.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/openssl.pc".store_path]
hash = "fyiwac98bi86nd5qzz9bhvs1bvmmwgad"
name = "openssl-3.0.8-dev"
store_dir = "/nix/store"

["lib/pkgconfig/openssl.pc".store_path.origin]
attr = "openssl"
output = "dev"
system = "x86_64-linux"
toplevel = true

["share/aclocal/ax_zoneinfo.m4"]
decision = "provide"
file_entry_name = "/share/aclocal/ax_zoneinfo.m4"
kind = "symlink"
resolution = "constant"

["share/aclocal/ax_zoneinfo.m4".store_path]
hash = "0znwn1lw0268i7pj0rylhz9dnzbwijjn"
name = "autoconf-archive-2022.09.03"
store_dir = "/nix/store"

["share/aclocal/ax_zoneinfo.m4".store_path.origin]
attr = "autoconf-archive"
output = "out"
system = "x86_64-linux"
toplevel = true
