["bin/cargo"]
decision = "provide"
file_entry_name = "/bin/cargo"
kind = "symlink"
resolution = "constant"

["bin/cargo".store_path]
hash = "qiklc9rr5jg1zck0rb7vj4wn1n7yxx67"
name = "cargo-1.67.1"
store_dir = "/nix/store"

["bin/cargo".store_path.origin]
attr = "cargo"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/gfortran"]
decision = "provide"
file_entry_name = "/bin/gfortran"
kind = "symlink"
resolution = "constant"

["bin/gfortran".store_path]
hash = "y4fkkgbylpqgadgq3n50x7g614sjbrmv"
name = "gfortran-wrapper-12.2.0"
store_dir = "/nix/store"

["bin/gfortran".store_path.origin]
attr = "gfortran"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/hg"]
decision = "provide"
file_entry_name = "/bin/hg"
kind = "symlink"
resolution = "constant"

["bin/hg".store_path]
hash = "v2s4kbgqfd0s9b6hd8b982azdca4m3l4"
name = "mercurial-6.3.3"
store_dir = "/nix/store"

["bin/hg".store_path.origin]
attr = "mercurial"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/lsb_release"]
decision = "provide"
file_entry_name = "/bin/lsb_release"
kind = "symlink"
resolution = "constant"

["bin/lsb_release".store_path]
hash = "ji55v58cch94h30inpnrd5h5jra9fwd8"
name = "lsb_release"
store_dir = "/nix/store"

["bin/lsb_release".store_path.origin]
attr = "lsb-release"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pgen"]
decision = "ignore"
resolution = "constant"

["bin/pip"]
decision = "provide"
file_entry_name = "/bin/pip"
kind = "symlink"
resolution = "constant"

["bin/pip".store_path]
hash = "8gzj48mkr8i824a4ali025hk85gmfdzy"
name = "python3.10-pip-22.3.1"
store_dir = "/nix/store"

["bin/pip".store_path.origin]
attr = "python310Packages.pip"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pkg-config"]
decision = "provide"
file_entry_name = "/bin/pkg-config"
kind = "symlink"
resolution = "constant"

["bin/pkg-config".store_path]
hash = "prm4x2r6997idyjxajapk1177jczvjfj"
name = "pkg-config-0.29.2"
store_dir = "/nix/store"

["bin/pkg-config".store_path.origin]
attr = "pkg-config-unwrapped"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/rustc"]
decision = "provide"
file_entry_name = "/bin/rustc"
kind = "symlink"
resolution = "constant"

["bin/rustc".store_path]
hash = "bxm02qp0lnm4sin3x78qrxp0gsbby1jb"
name = "rustc-1.67.1"
store_dir = "/nix/store"

["bin/rustc".store_path.origin]
attr = "rustc"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/svnversion"]
decision = "provide"
file_entry_name = "/bin/svnversion"
kind = "symlink"
resolution = "constant"

["bin/svnversion".store_path]
hash = "qz3yz8b3ahcjlnk96415gy3ldk0x36zw"
name = "subversion-1.14.2"
store_dir = "/nix/store"

["bin/svnversion".store_path.origin]
attr = "subversion"
output = "out"
system = "x86_64-linux"
toplevel = true

["include/GL"]
decision = "provide"
file_entry_name = "/include/GL"
kind = "directory"
resolution = "constant"

["include/GL".store_path]
hash = "v8yx8f5yc2vlkm9r6y17kmc6anclr3xd"
name = "mesa-22.3.5-dev"
store_dir = "/nix/store"

["include/GL".store_path.origin]
attr = "mesa"
output = "dev"
system = "x86_64-linux"
toplevel = true

["include/GL/gl.h"]
decision = "provide"
file_entry_name = "/include/GL/gl.h"
kind = "symlink"
resolution = "constant"

["include/GL/gl.h".store_path]
hash = "6rfffcxwpyxwwig234m0ika77lz7jw0z"
name = "nx-libs-3.5.99.26"
store_dir = "/nix/store"

["include/GL/gl.h".store_path.origin]
attr = "nx-libs"
output = "out"
system = "x86_64-linux"
toplevel = true

["include/X11"]
decision = "provide"
file_entry_name = "/include/X11"
kind = "directory"
resolution = "constant"

["include/X11".store_path]
hash = "75jd6r549krqxk1iq5cl4slrr4vci11n"
name = "libXtst-1.2.3"
store_dir = "/nix/store"

["include/X11".store_path.origin]
attr = "xorg.libXtst"
output = "out"
system = "x86_64-linux"
toplevel = true

["include/X11/X.h"]
decision = "provide"
file_entry_name = "/include/X11/X.h"
kind = "symlink"
resolution = "constant"

["include/X11/X.h".store_path]
hash = "9d1fbfvijywjsxh5b060qy5dd01cqbrs"
name = "xorgproto-2021.5"
store_dir = "/nix/store"

["include/X11/X.h".store_path.origin]
attr = "xorg.xorgproto"
output = "out"
system = "x86_64-linux"
toplevel = true

["include/X11/Xlib.h"]
decision = "provide"
file_entry_name = "/include/X11/Xlib.h"
kind = "symlink"
resolution = "constant"

["include/X11/Xlib.h".store_path]
hash = "q2sjb83p9kh7j653237wr5xzsdc17sgj"
name = "libX11-1.8.4-dev"
store_dir = "/nix/store"

["include/X11/Xlib.h".store_path.origin]
attr = "xorg.libX11"
output = "dev"
system = "x86_64-linux"
toplevel = true

["include/libunwind.h"]
decision = "ignore"
resolution = "constant"

["include/sys"]
decision = "ignore"
resolution = "constant"

["include/sys/endian.h"]
decision = "ignore"
resolution = "constant"

["include/tbb"]
decision = "ignore"
resolution = "constant"

["include/xlocale.h"]
decision = "ignore"
resolution = "constant"

["lib/libGL.so"]
decision = "provide"
file_entry_name = "/lib/libGL.so"
kind = "symlink"
resolution = "constant"

["lib/libGL.so".store_path]
hash = "2hq6cv8cmfz35mr6i8whxf49x3hy2h30"
name = "qt-full-6.4.2"
store_dir = "/nix/store"

["lib/libGL.so".store_path.origin]
attr = "qt6.full"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/SDL2_image.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/SDL2_image.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/SDL2_image.pc".store_path]
hash = "5ni7kgzydxg2f8wcf95c0lkmyyms8sfl"
name = "SDL2_image-2.0.5"
store_dir = "/nix/store"

["lib/pkgconfig/SDL2_image.pc".store_path.origin]
attr = "SDL2_image_2_0_5"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/SDL2_mixer.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/SDL2_mixer.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/SDL2_mixer.pc".store_path]
hash = "wvzqp9gx4jpcz21826ss9qmbhgi069gy"
name = "SDL2_mixer-2.0.4-dev"
store_dir = "/nix/store"

["lib/pkgconfig/SDL2_mixer.pc".store_path.origin]
attr = "SDL2_mixer_2_0"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/SDL2_ttf.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/SDL2_ttf.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/SDL2_ttf.pc".store_path]
hash = "jj3zqq05010sq5r75aq9yzq3hr4ldndr"
name = "SDL2_ttf-2.20.2"
store_dir = "/nix/store"

["lib/pkgconfig/SDL2_ttf.pc".store_path.origin]
attr = "SDL2_ttf"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/fontconfig.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/fontconfig.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/fontconfig.pc".store_path]
hash = "6bdds6632r9fp7mrh27qxjv90d7lzh0y"
name = "fontconfig-2.14.0-dev"
store_dir = "/nix/store"

["lib/pkgconfig/fontconfig.pc".store_path.origin]
attr = "fontconfig"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/freetype2.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/freetype2.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/freetype2.pc".store_path]
hash = "ybd7brnb5kavanvz40mg2p5pmgnczi85"
name = "freetype-2.12.1-dev"
store_dir = "/nix/store"

["lib/pkgconfig/freetype2.pc".store_path.origin]
attr = "freetype"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/glib-2.0.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/glib-2.0.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/glib-2.0.pc".store_path]
hash = "152gsygyjagsirvdg3icmz4px39wddwj"
name = "glib-2.74.5-dev"
store_dir = "/nix/store"

["lib/pkgconfig/glib-2.0.pc".store_path.origin]
attr = "glib"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/gstreamer-1.0.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/gstreamer-1.0.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/gstreamer-1.0.pc".store_path]
hash = "g5j4h69kshx1ydmfl9xq4kasfp7zk5di"
name = "gstreamer-1.20.3-dev"
store_dir = "/nix/store"

["lib/pkgconfig/gstreamer-1.0.pc".store_path.origin]
attr = "gst_all_1.gstreamer"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/harfbuzz.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/harfbuzz.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/harfbuzz.pc".store_path]
hash = "vddrjv0wnknv73njnwzj3in0467dk9qa"
name = "harfbuzz-7.0.0-dev"
store_dir = "/nix/store"

["lib/pkgconfig/harfbuzz.pc".store_path.origin]
attr = "harfbuzz"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/libffi.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/libffi.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/libffi.pc".store_path]
hash = "4j08mgygxhi9y3957hbwqn1bg02va18y"
name = "libffi-3.4.4-dev"
store_dir = "/nix/store"

["lib/pkgconfig/libffi.pc".store_path.origin]
attr = "libffi"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/openssl.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/openssl.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/openssl.pc".store_path]
hash = "fyiwac98bi86nd5qzz9bhvs1bvmmwgad"
name = "openssl-3.0.8-dev"
store_dir = "/nix/store"

["lib/pkgconfig/openssl.pc".store_path.origin]
attr = "openssl"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/pangoft2.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/pangoft2.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/pangoft2.pc".store_path]
hash = "36z48v5b6x165cpp43z64mrfyv09vzv4"
name = "pango-1.50.12-dev"
store_dir = "/nix/store"

["lib/pkgconfig/pangoft2.pc".store_path.origin]
attr = "pango"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/sdl2.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/sdl2.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/sdl2.pc".store_path]
hash = "738ld2bma43h4s0wcfyasm07k863cvgj"
name = "SDL2-2.24.2-dev"
store_dir = "/nix/store"

["lib/pkgconfig/sdl2.pc".store_path.origin]
attr = "SDL2"
output = "dev"
system = "x86_64-linux"
toplevel = true

["share/aclocal/ax_zoneinfo.m4"]
decision = "provide"
file_entry_name = "/share/aclocal/ax_zoneinfo.m4"
kind = "symlink"
resolution = "constant"

["share/aclocal/ax_zoneinfo.m4".store_path]
hash = "0znwn1lw0268i7pj0rylhz9dnzbwijjn"
name = "autoconf-archive-2022.09.03"
store_dir = "/nix/store"

["share/aclocal/ax_zoneinfo.m4".store_path.origin]
attr = "autoconf-archive"
output = "out"
system = "x86_64-linux"
toplevel = true
