["bin/cargo"]
decision = "provide"
file_entry_name = "/bin/cargo"
kind = "symlink"
resolution = "constant"

["bin/cargo".store_path]
hash = "qiklc9rr5jg1zck0rb7vj4wn1n7yxx67"
name = "cargo-1.67.1"
store_dir = "/nix/store"

["bin/cargo".store_path.origin]
attr = "cargo"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/gfortran"]
decision = "provide"
file_entry_name = "/bin/gfortran"
kind = "symlink"
resolution = "constant"

["bin/gfortran".store_path]
hash = "y4fkkgbylpqgadgq3n50x7g614sjbrmv"
name = "gfortran-wrapper-12.2.0"
store_dir = "/nix/store"

["bin/gfortran".store_path.origin]
attr = "gfortran"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/hostname"]
decision = "provide"
file_entry_name = "/bin/hostname"
kind = "symlink"
resolution = "constant"

["bin/hostname".store_path]
hash = "frsfkmk6ywb7wilhzyg2f8wczyacji86"
name = "net-tools-2.10"
store_dir = "/nix/store"

["bin/hostname".store_path.origin]
attr = "nettools"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/lsb_release"]
decision = "provide"
file_entry_name = "/bin/lsb_release"
kind = "symlink"
resolution = "constant"

["bin/lsb_release".store_path]
hash = "ji55v58cch94h30inpnrd5h5jra9fwd8"
name = "lsb_release"
store_dir = "/nix/store"

["bin/lsb_release".store_path.origin]
attr = "lsb-release"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pgen"]
decision = "ignore"
resolution = "constant"

["bin/pip"]
decision = "provide"
file_entry_name = "/bin/pip"
kind = "symlink"
resolution = "constant"

["bin/pip".store_path]
hash = "8gzj48mkr8i824a4ali025hk85gmfdzy"
name = "python3.10-pip-22.3.1"
store_dir = "/nix/store"

["bin/pip".store_path.origin]
attr = "python310Packages.pip"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/pkg-config"]
decision = "provide"
file_entry_name = "/bin/pkg-config"
kind = "symlink"
resolution = "constant"

["bin/pkg-config".store_path]
hash = "prm4x2r6997idyjxajapk1177jczvjfj"
name = "pkg-config-0.29.2"
store_dir = "/nix/store"

["bin/pkg-config".store_path.origin]
attr = "pkg-config-unwrapped"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/rustc"]
decision = "provide"
file_entry_name = "/bin/rustc"
kind = "symlink"
resolution = "constant"

["bin/rustc".store_path]
hash = "bxm02qp0lnm4sin3x78qrxp0gsbby1jb"
name = "rustc-1.67.1"
store_dir = "/nix/store"

["bin/rustc".store_path.origin]
attr = "rustc"
output = "out"
system = "x86_64-linux"
toplevel = true

["bin/svnversion"]
decision = "provide"
file_entry_name = "/bin/svnversion"
kind = "symlink"
resolution = "constant"

["bin/svnversion".store_path]
hash = "qz3yz8b3ahcjlnk96415gy3ldk0x36zw"
name = "subversion-1.14.2"
store_dir = "/nix/store"

["bin/svnversion".store_path.origin]
attr = "subversion"
output = "out"
system = "x86_64-linux"
toplevel = true

["include/bzlib.h"]
decision = "provide"
file_entry_name = "/include/bzlib.h"
kind = "symlink"
resolution = "constant"

["include/bzlib.h".store_path]
hash = "abs0rlwm6jh4l1k831fvqggpgfrs91pv"
name = "bzip2-1.0.8-dev"
store_dir = "/nix/store"

["include/bzlib.h".store_path.origin]
attr = "bzip2"
output = "dev"
system = "x86_64-linux"
toplevel = true

["include/curl"]
decision = "provide"
file_entry_name = "/include/curl"
kind = "directory"
resolution = "constant"

["include/curl".store_path]
hash = "gd51gknpxqaxyd0gycmszm8ckrvwvs0l"
name = "curl-7.88.0-dev"
store_dir = "/nix/store"

["include/curl".store_path.origin]
attr = "curl"
output = "dev"
system = "x86_64-linux"
toplevel = true

["include/libdeflate.h"]
decision = "provide"
file_entry_name = "/include/libdeflate.h"
kind = "symlink"
resolution = "constant"

["include/libdeflate.h".store_path]
hash = "al2c9nyjfmkk1hx8606j56vh2i1m1anc"
name = "libdeflate-1.17"
store_dir = "/nix/store"

["include/libdeflate.h".store_path.origin]
attr = "libdeflate"
output = "out"
system = "x86_64-linux"
toplevel = true

["include/libunwind.h"]
decision = "ignore"
resolution = "constant"

["include/lzma.h"]
decision = "provide"
file_entry_name = "/include/lzma.h"
kind = "symlink"
resolution = "constant"

["include/lzma.h".store_path]
hash = "zfrjyd3s96gzdvnmdw9i3n7mqqcipx3l"
name = "xz-5.4.1-dev"
store_dir = "/nix/store"

["include/lzma.h".store_path.origin]
attr = "xz"
output = "dev"
system = "x86_64-linux"
toplevel = true

["include/sys"]
decision = "ignore"
resolution = "constant"

["include/sys/endian.h"]
decision = "ignore"
resolution = "constant"

["include/tbb"]
decision = "ignore"
resolution = "constant"

["include/xlocale.h"]
decision = "ignore"
resolution = "constant"

["include/zlib.h"]
decision = "provide"
file_entry_name = "/include/zlib.h"
kind = "symlink"
resolution = "constant"

["include/zlib.h".store_path]
hash = "qgqsyg7gmqy3fz6shvzhcc7m7pkfw2ig"
name = "zlib-1.2.13-dev"
store_dir = "/nix/store"

["include/zlib.h".store_path.origin]
attr = "zlib"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/libbz2.so"]
decision = "provide"
file_entry_name = "/lib/libbz2.so"
kind = "symlink"
resolution = "constant"

["lib/libbz2.so".store_path]
hash = "k0yrr5yq9yghbvvfv0qkblyia576kg4f"
name = "bzip2-1.0.8"
store_dir = "/nix/store"

["lib/libbz2.so".store_path.origin]
attr = "bzip2"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/libcrypto.so"]
decision = "provide"
file_entry_name = "/lib/libcrypto.so"
kind = "symlink"
resolution = "constant"

["lib/libcrypto.so".store_path]
hash = "xgcmx3kjp8xah262a1yd948y6pbqy7mn"
name = "quictls-3.0.8+quic"
store_dir = "/nix/store"

["lib/libcrypto.so".store_path.origin]
attr = "quictls"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/libcurl.so"]
decision = "provide"
file_entry_name = "/lib/libcurl.so"
kind = "symlink"
resolution = "constant"

["lib/libcurl.so".store_path]
hash = "4bx5nibwwi6dwbd75yg9kw1hcxikifjh"
name = "curl-7.88.0"
store_dir = "/nix/store"

["lib/libcurl.so".store_path.origin]
attr = "curlHTTP3"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/liblzma.so"]
decision = "provide"
file_entry_name = "/lib/liblzma.so"
kind = "symlink"
resolution = "constant"

["lib/liblzma.so".store_path]
hash = "wfz3rd51ka009f3l4g6gh7innyf0gq2f"
name = "xz-5.4.1"
store_dir = "/nix/store"

["lib/liblzma.so".store_path.origin]
attr = "xz"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/libz.so"]
decision = "provide"
file_entry_name = "/lib/libz.so"
kind = "symlink"
resolution = "constant"

["lib/libz.so".store_path]
hash = "mg9l7phyhvi16p9g8g3g8fbyj4mr79gq"
name = "zlib-1.2.13"
store_dir = "/nix/store"

["lib/libz.so".store_path.origin]
attr = "zlib"
output = "out"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/libffi.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/libffi.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/libffi.pc".store_path]
hash = "4j08mgygxhi9y3957hbwqn1bg02va18y"
name = "libffi-3.4.4-dev"
store_dir = "/nix/store"

["lib/pkgconfig/libffi.pc".store_path.origin]
attr = "libffi"
output = "dev"
system = "x86_64-linux"
toplevel = true

["lib/pkgconfig/openssl.pc"]
decision = "provide"
file_entry_name = "/lib/pkgconfig/openssl.pc"
kind = "symlink"
resolution = "constant"

["lib/pkgconfig/openssl.pc".store_path]
hash = "fyiwac98bi86nd5qzz9bhvs1bvmmwgad"
name = "openssl-3.0.8-dev"
store_dir = "/nix/store"

["lib/pkgconfig/openssl.pc".store_path.origin]
attr = "openssl"
output = "dev"
system = "x86_64-linux"
toplevel = true

["share/aclocal/ax_zoneinfo.m4"]
decision = "provide"
file_entry_name = "/share/aclocal/ax_zoneinfo.m4"
kind = "symlink"
resolution = "constant"

["share/aclocal/ax_zoneinfo.m4".store_path]
hash = "0znwn1lw0268i7pj0rylhz9dnzbwijjn"
name = "autoconf-archive-2022.09.03"
store_dir = "/nix/store"

["share/aclocal/ax_zoneinfo.m4".store_path.origin]
attr = "autoconf-archive"
output = "out"
system = "x86_64-linux"
toplevel = true
